### ISSUE TITLE
你好 如何转发到企业微信之类的呢？

### ISSUE THREAD

**Issue by an429075824** [SmsForwardCenter/ZxicSmsFwd#1]
大牛  可以出个详细教程嘛？现在有锁的就10多元。破解了可以插自己的卡，如果用玩客云搭建个终端  插中兴微的设备 如何转发短信出去呢？

**Comment by MisakaMikoto-35c5** [comment]
1. 不会添加对企业微信的支持，因为我没有企业微信，但是如果有人实现了欢迎提交 Pull Request；
2. 破解的方法这边不会提供；
3. 在 Linux 上搭建可以参考[我的博客文章](https://blog.wsl.moe/2022/01/%E5%9F%BA%E4%BA%8E%E4%B8%AD%E5%85%B4%E5%BE%AE%E7%94%B5%E5%AD%90%E6%96%B9%E6%A1%88%E7%9A%84-usb-lte-dongle-%E5%AE%9E%E7%8E%B0%E7%9A%84%E7%9F%AD%E4%BF%A1%E8%BD%AC%E5%8F%91%E5%99%A8/)。

**Comment by an429075824** [comment]
Systemd User Service 这个可以安装到debian的嘛？如果安装这个 驱动问题是怎么解决的？没有看懂😂破解esim卡,这个我会😂

**Comment by MisakaMikoto-35c5** [comment]
Systemd User Service 是 systemd 的功能，让没有 root 权限的用户可以安装自己的 systemd 服务，以及实现开机自启。详情请参考[Arch Linux Wiki](https://wiki.archlinuxcn.org/wiki/Systemd/User)。

Systemd 在 Debian 8 以上都默认安装了，除非是 Docker 这种环境。此外，Docker 也不需要使用 systemd，直接 `python3 zxicsmsfwd` 作为 Start Command 运行起来就可以了。

关于驱动问题，中兴方案的 LTE USB Dongle 用 RNDIS 在 USB 上提供服务，我自己测试树莓派是可以直接用的。如果是 OpenWRT，可能需要安装 `kmod-usb-net-rndis` 这个 Kmod 才能用。至于玩客云的话，可能是编译你的固件的时候内核选项没有勾 RNDIS Support。

另外说一下，如果有很多同样的设备，需要自己把设备 IP 修改一下来避免冲突。

**Comment by an429075824** [comment]
感谢大牛,之前有把玩客云刷了debian安装了gammu但是驱动问题没有解决,昨天偶然看到你的方案,简直是太完美了👍我研究一下！

**Comment by an429075824** [comment]
大佬 还得请教下🙏
我玩客云刷了armdian 显示是linux10 。
按博客步骤操作systemd User Service 没有找到~/.config/.config/systemd/user/zxicsmsfwd.service 这个路径。
我把zxicsmsfwd.service放在了/usr/lib/systemd/system下面,设置了开机启动。
接下来都很顺利，到最后的时候提示这个👇
root@onecloud:~# systemctl --user start zxicsmsfwd
Failed to connect to bus: Connection refused
不知道是墙内连不上电报还是别的原因！
我如果要改企业微信或者别的推送服务是需要修改config_utils.py 嘛？

**Comment by MisakaMikoto-35c5** [comment]
这个是 systemd 的问题，不是这个项目的问题，详情请参考[Arch Linux Wiki](https://wiki.archlinuxcn.org/wiki/Systemd/User)，或是自行查询解决方案，抑或是不通过 systemd 直接运行。

**Comment by an429075824** [comment]
大佬 帮帮忙  折腾3天了 还是启动失败呢

● zxicsmsfwd.service - ZXIC based LTE dongle SMS forwarder
     Loaded: loaded (/etc/systemd/system/zxicsmsfwd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2023-03-19 00:58:19 CST; 12s ago
    Process: 2017 ExecStart=/usr/bin/env python3 zxicsmsfwd (code=exited, status=200/CHDIR)
   Main PID: 2017 (code=exited, status=200/CHDIR)
        CPU: 5ms

Mar 19 00:58:19 onecloud systemd[1]: zxicsmsfwd.service: Scheduled restart job, restart counter is at 5.
Mar 19 00:58:19 onecloud systemd[1]: Stopped ZXIC based LTE dongle SMS forwarder.
Mar 19 00:58:19 onecloud systemd[1]: zxicsmsfwd.service: Start request repeated too quickly.
Mar 19 00:58:19 onecloud systemd[1]: zxicsmsfwd.service: Failed with result 'exit-code'.
Mar 19 00:58:19 onecloud systemd[1]: Failed to start ZXIC based LTE dongle SMS forwarder.

**Comment by MisakaMikoto-35c5** [comment]
把 `/etc/systemd/system/zxicsmsfwd.service` 的文件内容放上来看一下？其次，直接在安装目录下使用命令 `python3 zxicsmsfwd` 运行试一下？

其次，User Service 的问题我发现实际上是文章里面 `.service` 文件的路径写错了，应该是 `~/.config/systemd/user/zxicsmsfwd.service` 才是正确的。

**Comment by an429075824** [comment]
我把zxicsmsfwd.service文件放到了etc下面 更新完配置以后 切换到安装目录 运行了py3 提示没有找到main 
`root@onecloud:/change/to/your/installation/path/for# python3 zxicsmsfwd `
`/usr/bin/python3:` can't find '__main__' module in `'/change/to/your/installation/path/for/zxicsmsfwd'`
User Service 目录我没有放错，是不是armbian缺少什么运行库？还有系统默认py的版本是2.7

**Comment by an429075824** [comment]
切到这个目录`/change/to/your/installation/path/for/zxicsmsfwd/zxicsmsfwd`运行`python3 zxicsmsfwd`
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/change/to/your/installation/path/for/zxicsmsfwd/zxicsmsfwd/__main__.py", line 1, in <module>
    import sms_forwarder
  File "/change/to/your/installation/path/for/zxicsmsfwd/zxicsmsfwd/sms_forwarder.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

**Comment by an429075824** [comment]
安装了`requests` 好像成功了Send Telegram message failed. 发送失败我怀疑是被墙的问题！感谢大佬，当初买了5，6个中兴微方案的随身wifi可是用有了。

**Comment by an429075824** [comment]
启动失败的问题解决了，我没有按照博客的步骤弄，直接复制了github上的`zxicsmsfwd.service`
github上的目录不是/change/to/your/installation/path/for/zxicsmsfwd
最主要的原因是英文不OK，没有看懂/change/to/your/installation/path/for/ 这是什么意思

大佬要有打算研究企业微信或者别的推送方式 我可以提供企业微信的密匙测试
